### ISSUE TITLE
Bought the Paid version (AndroidIDeditorV2-1.3-release.apk)

### ISSUE THREAD

**Issue by filzek** [sdex/AndroidIDeditorV2#1]
Hi,

I bought the paid version and its working fine.

We need to use in a simple way, could you please help to solve this, as we need to do it from adb shell to change the  triple ID from:
Amazon
Device
Windows Subsystem

it can be random not a problem and need to restart the system.

if its avaliable now please let me know how to do it.

my key is E4117DD4-xxxxxxxx-98EBE7F4-6B12E306

**Comment by sdex** [comment]
Hi @filzek 

The app is not designed to be run from the command line and I don't have plans to add such capabilities. You need a custom solution that fits your needs. 
As a workaround, you can try to use some 3rd party automation apps or send input events using adb:
`adb shell input swipe/tap`
