### ISSUE TITLE
I can not pay with paypal

### ISSUE THREAD

**Issue by Baraasuliman** [sdex/AndroidIDeditorV2#2]
![Screenshot_20230413-223030_Brave](https://user-images.githubusercontent.com/95190705/231876108-4ff41db3-9809-4d0f-a0fe-b1df74255ee3.png)
When I try to pay with PayPal does not work do you have a PayPal?

**Comment by sdex** [comment]
Unfortunately, I don't know what happened and how to resolve it. I linked my Paypal account and haven't seen any issues until now.
